/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoramatrices3x3;

import javax.swing.JTextField;

/**
 *
 * @author juanc
 */
public class InterfaceCalc extends javax.swing.JFrame {
    private int i;
    private int j;
    private int k;
    /**
     * Creates new form InterfaceCalc
     */
    public InterfaceCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        MatrizA = new javax.swing.JPanel();
        TagA = new javax.swing.JLabel();
        A11 = new javax.swing.JTextField();
        A12 = new javax.swing.JTextField();
        A13 = new javax.swing.JTextField();
        A21 = new javax.swing.JTextField();
        A22 = new javax.swing.JTextField();
        A23 = new javax.swing.JTextField();
        A31 = new javax.swing.JTextField();
        A32 = new javax.swing.JTextField();
        A33 = new javax.swing.JTextField();
        MatrizB = new javax.swing.JPanel();
        TagB = new javax.swing.JLabel();
        B11 = new javax.swing.JTextField();
        B12 = new javax.swing.JTextField();
        B13 = new javax.swing.JTextField();
        B21 = new javax.swing.JTextField();
        B22 = new javax.swing.JTextField();
        B23 = new javax.swing.JTextField();
        B31 = new javax.swing.JTextField();
        B32 = new javax.swing.JTextField();
        B33 = new javax.swing.JTextField();
        MatrizC = new javax.swing.JPanel();
        TagC = new javax.swing.JLabel();
        C11 = new javax.swing.JTextField();
        C12 = new javax.swing.JTextField();
        C13 = new javax.swing.JTextField();
        C21 = new javax.swing.JTextField();
        C22 = new javax.swing.JTextField();
        C23 = new javax.swing.JTextField();
        C31 = new javax.swing.JTextField();
        C32 = new javax.swing.JTextField();
        C33 = new javax.swing.JTextField();
        SUMA = new javax.swing.JButton();
        RESTA = new javax.swing.JButton();
        MULTI = new javax.swing.JButton();
        INVERSA = new javax.swing.JButton();
        DetA = new javax.swing.JButton();
        ax = new javax.swing.JLabel();
        TITULO = new javax.swing.JLabel();
        Det = new javax.swing.JLabel();
        CLEAN = new javax.swing.JButton();
        TrasA = new javax.swing.JButton();
        Marca1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MatrizA.setBackground(new java.awt.Color(204, 255, 255));
        MatrizA.setPreferredSize(new java.awt.Dimension(235, 235));

        TagA.setForeground(new java.awt.Color(0, 0, 0));
        TagA.setText("A");
        TagA.setName(""); // NOI18N

        A11.setBackground(new java.awt.Color(255, 255, 255));
        A11.setForeground(new java.awt.Color(0, 0, 0));
        A11.setName("A11"); // NOI18N
        A11.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                A11InputMethodTextChanged(evt);
            }
        });
        A11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A11ActionPerformed(evt);
            }
        });

        A12.setBackground(new java.awt.Color(255, 255, 255));
        A12.setForeground(new java.awt.Color(0, 0, 0));

        A13.setBackground(new java.awt.Color(255, 255, 255));
        A13.setForeground(new java.awt.Color(0, 0, 0));

        A21.setBackground(new java.awt.Color(255, 255, 255));
        A21.setForeground(new java.awt.Color(0, 0, 0));

        A22.setBackground(new java.awt.Color(255, 255, 255));
        A22.setForeground(new java.awt.Color(0, 0, 0));

        A23.setBackground(new java.awt.Color(255, 255, 255));
        A23.setForeground(new java.awt.Color(0, 0, 0));

        A31.setBackground(new java.awt.Color(255, 255, 255));
        A31.setForeground(new java.awt.Color(0, 0, 0));

        A32.setBackground(new java.awt.Color(255, 255, 255));
        A32.setForeground(new java.awt.Color(0, 0, 0));

        A33.setBackground(new java.awt.Color(255, 255, 255));
        A33.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout MatrizALayout = new javax.swing.GroupLayout(MatrizA);
        MatrizA.setLayout(MatrizALayout);
        MatrizALayout.setHorizontalGroup(
            MatrizALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrizALayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(MatrizALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TagA)
                    .addGroup(MatrizALayout.createSequentialGroup()
                        .addComponent(A31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(A32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(A33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MatrizALayout.createSequentialGroup()
                        .addComponent(A21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(A22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(A23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MatrizALayout.createSequentialGroup()
                        .addComponent(A11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(A12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(A13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        MatrizALayout.setVerticalGroup(
            MatrizALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrizALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TagA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MatrizALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MatrizALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MatrizALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        A11.getAccessibleContext().setAccessibleName("A11");
        A12.getAccessibleContext().setAccessibleName("A12");
        A13.getAccessibleContext().setAccessibleName("A13");
        A21.getAccessibleContext().setAccessibleName("A21");
        A22.getAccessibleContext().setAccessibleName("A22");
        A23.getAccessibleContext().setAccessibleName("A23");
        A31.getAccessibleContext().setAccessibleName("A31");
        A31.getAccessibleContext().setAccessibleDescription("");
        A32.getAccessibleContext().setAccessibleName("A32");
        A33.getAccessibleContext().setAccessibleName("A33");
        A33.getAccessibleContext().setAccessibleDescription("");

        MatrizB.setBackground(new java.awt.Color(255, 204, 204));
        MatrizB.setPreferredSize(new java.awt.Dimension(235, 235));

        TagB.setForeground(new java.awt.Color(0, 0, 0));
        TagB.setText("B");

        B11.setBackground(new java.awt.Color(255, 255, 255));
        B11.setForeground(new java.awt.Color(0, 0, 0));

        B12.setBackground(new java.awt.Color(255, 255, 255));
        B12.setForeground(new java.awt.Color(0, 0, 0));

        B13.setBackground(new java.awt.Color(255, 255, 255));
        B13.setForeground(new java.awt.Color(0, 0, 0));

        B21.setBackground(new java.awt.Color(255, 255, 255));
        B21.setForeground(new java.awt.Color(0, 0, 0));

        B22.setBackground(new java.awt.Color(255, 255, 255));
        B22.setForeground(new java.awt.Color(0, 0, 0));

        B23.setBackground(new java.awt.Color(255, 255, 255));
        B23.setForeground(new java.awt.Color(0, 0, 0));

        B31.setBackground(new java.awt.Color(255, 255, 255));
        B31.setForeground(new java.awt.Color(0, 0, 0));

        B32.setBackground(new java.awt.Color(255, 255, 255));
        B32.setForeground(new java.awt.Color(0, 0, 0));

        B33.setBackground(new java.awt.Color(255, 255, 255));
        B33.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout MatrizBLayout = new javax.swing.GroupLayout(MatrizB);
        MatrizB.setLayout(MatrizBLayout);
        MatrizBLayout.setHorizontalGroup(
            MatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrizBLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(TagB)
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(MatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MatrizBLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(MatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MatrizBLayout.createSequentialGroup()
                            .addComponent(B31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(B32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(B33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MatrizBLayout.createSequentialGroup()
                            .addComponent(B21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(B22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(B23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MatrizBLayout.createSequentialGroup()
                            .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(B12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(B13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        MatrizBLayout.setVerticalGroup(
            MatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrizBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TagB)
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(MatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MatrizBLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(MatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(MatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(MatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        B11.getAccessibleContext().setAccessibleName("B11");
        B12.getAccessibleContext().setAccessibleName("B12");
        B13.getAccessibleContext().setAccessibleName("B13");
        B21.getAccessibleContext().setAccessibleName("B21");
        B22.getAccessibleContext().setAccessibleName("B22");
        B23.getAccessibleContext().setAccessibleName("B23");
        B31.getAccessibleContext().setAccessibleName("B31");
        B32.getAccessibleContext().setAccessibleName("B32");
        B33.getAccessibleContext().setAccessibleName("B33");
        B33.getAccessibleContext().setAccessibleDescription("");

        MatrizC.setBackground(new java.awt.Color(204, 255, 204));
        MatrizC.setPreferredSize(new java.awt.Dimension(235, 235));

        TagC.setForeground(new java.awt.Color(0, 0, 0));
        TagC.setText("C");

        C11.setBackground(new java.awt.Color(255, 255, 255));
        C11.setForeground(new java.awt.Color(0, 0, 0));

        C12.setBackground(new java.awt.Color(255, 255, 255));
        C12.setForeground(new java.awt.Color(0, 0, 0));

        C13.setBackground(new java.awt.Color(255, 255, 255));
        C13.setForeground(new java.awt.Color(0, 0, 0));

        C21.setBackground(new java.awt.Color(255, 255, 255));
        C21.setForeground(new java.awt.Color(0, 0, 0));

        C22.setBackground(new java.awt.Color(255, 255, 255));
        C22.setForeground(new java.awt.Color(0, 0, 0));

        C23.setBackground(new java.awt.Color(255, 255, 255));
        C23.setForeground(new java.awt.Color(0, 0, 0));

        C31.setBackground(new java.awt.Color(255, 255, 255));
        C31.setForeground(new java.awt.Color(0, 0, 0));

        C32.setBackground(new java.awt.Color(255, 255, 255));
        C32.setForeground(new java.awt.Color(0, 0, 0));

        C33.setBackground(new java.awt.Color(255, 255, 255));
        C33.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout MatrizCLayout = new javax.swing.GroupLayout(MatrizC);
        MatrizC.setLayout(MatrizCLayout);
        MatrizCLayout.setHorizontalGroup(
            MatrizCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrizCLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TagC)
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(MatrizCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MatrizCLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(MatrizCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MatrizCLayout.createSequentialGroup()
                            .addComponent(C31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(C32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(C33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MatrizCLayout.createSequentialGroup()
                            .addComponent(C21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(C22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(C23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MatrizCLayout.createSequentialGroup()
                            .addComponent(C11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(C12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(C13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        MatrizCLayout.setVerticalGroup(
            MatrizCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrizCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TagC)
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(MatrizCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MatrizCLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(MatrizCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(C11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(C12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(C13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(MatrizCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(C21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(C22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(C23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(MatrizCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(C31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(C32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(C33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        C11.getAccessibleContext().setAccessibleName("C11");
        C12.getAccessibleContext().setAccessibleName("C12");
        C13.getAccessibleContext().setAccessibleName("C13");
        C21.getAccessibleContext().setAccessibleName("C21");
        C22.getAccessibleContext().setAccessibleName("C22");
        C23.getAccessibleContext().setAccessibleName("C23");
        C31.getAccessibleContext().setAccessibleName("C31");
        C32.getAccessibleContext().setAccessibleName("C32");
        C33.getAccessibleContext().setAccessibleName("C33");

        SUMA.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        SUMA.setLabel("+");
        SUMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUMAActionPerformed(evt);
            }
        });

        RESTA.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        RESTA.setText("-");
        RESTA.setMaximumSize(new java.awt.Dimension(42, 44));
        RESTA.setMinimumSize(new java.awt.Dimension(42, 44));
        RESTA.setPreferredSize(new java.awt.Dimension(42, 44));
        RESTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESTAActionPerformed(evt);
            }
        });

        MULTI.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        MULTI.setText("x");
        MULTI.setMaximumSize(new java.awt.Dimension(42, 44));
        MULTI.setMinimumSize(new java.awt.Dimension(42, 44));
        MULTI.setPreferredSize(new java.awt.Dimension(42, 44));
        MULTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULTIActionPerformed(evt);
            }
        });

        INVERSA.setText("INVERSA DE A");
        INVERSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INVERSAActionPerformed(evt);
            }
        });

        DetA.setText("DETERMINANTE DE A");
        DetA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetAActionPerformed(evt);
            }
        });

        ax.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        TITULO.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TITULO.setText("CALCULADORA DE MATRICES 3X3");

        Det.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Det.setText("Determinante:");

        CLEAN.setText("Limpiar");
        CLEAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEANActionPerformed(evt);
            }
        });

        TrasA.setText("TRASPUESTA DE A");
        TrasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrasAActionPerformed(evt);
            }
        });

        Marca1.setText("Juan Esteban Chaparro Gutiérrez");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MatrizA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MULTI, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SUMA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RESTA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MatrizB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CLEAN)
                            .addComponent(Marca1))
                        .addGap(167, 167, 167)
                        .addComponent(MatrizC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addComponent(Det)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MenuLayout.createSequentialGroup()
                                        .addComponent(INVERSA)
                                        .addGap(18, 18, 18)
                                        .addComponent(DetA))
                                    .addComponent(TrasA))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(TITULO)))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TITULO)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SUMA)
                        .addGap(19, 19, 19)
                        .addComponent(RESTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MULTI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MatrizB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(MatrizA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)))
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(INVERSA)
                            .addComponent(DetA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Det)
                            .addComponent(ax, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(TrasA))
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(MenuLayout.createSequentialGroup()
                            .addComponent(CLEAN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Marca1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(97, 97, 97))
                        .addComponent(MatrizC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );

        MatrizA.getAccessibleContext().setAccessibleName("A");
        MatrizA.getAccessibleContext().setAccessibleDescription("");
        MatrizB.getAccessibleContext().setAccessibleName("B");
        MatrizC.getAccessibleContext().setAccessibleName("C");
        SUMA.getAccessibleContext().setAccessibleName("SUMA");
        RESTA.getAccessibleContext().setAccessibleName("RESTA");
        MULTI.getAccessibleContext().setAccessibleName("MULTI");
        INVERSA.getAccessibleContext().setAccessibleName("Inversa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MULTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTIActionPerformed
        // TODO add your handling code here:
        int [][] A = new int[3][3];
        A[0][0]=Integer.parseInt(A11.getText());
        A[0][1]=Integer.parseInt(A12.getText());
        A[0][2]=Integer.parseInt(A13.getText());
        A[1][0]=Integer.parseInt(A21.getText());
        A[1][1]=Integer.parseInt(A22.getText());
        A[1][2]=Integer.parseInt(A23.getText());
        A[2][0]=Integer.parseInt(A31.getText());
        A[2][1]=Integer.parseInt(A32.getText());
        A[2][2]=Integer.parseInt(A33.getText());
     
        int [][] B = new int[3][3];
        B[0][0]=Integer.parseInt(B11.getText());
        B[0][1]=Integer.parseInt(B12.getText());
        B[0][2]=Integer.parseInt(B13.getText());
        B[1][0]=Integer.parseInt(B21.getText());
        B[1][1]=Integer.parseInt(B22.getText());
        B[1][2]=Integer.parseInt(B23.getText());
        B[2][0]=Integer.parseInt(B31.getText());
        B[2][1]=Integer.parseInt(B32.getText());
        B[2][2]=Integer.parseInt(B33.getText());
       int [][] C = new int[3][3];
       
         for (i=0; i<=2; i++){
             for (j=0; j<=2; j++){
             
                 for (k = 0; k <=2; k++) { 
                      for (k = 0; k <=2; k++) { 
                    C[i][j] += A[i][k] * B[k][j];
                      }
                 }
             }
             }
        
         C11.setText(String.valueOf (C[0][0]));
         C12.setText(String.valueOf (C[0][1]));
         C13.setText(String.valueOf (C[0][2]));
         C21.setText(String.valueOf (C[1][0]));
         C22.setText(String.valueOf (C[1][1]));
         C23.setText(String.valueOf (C[1][2]));
         C31.setText(String.valueOf (C[2][0]));
         C32.setText(String.valueOf (C[2][1]));
         C33.setText(String.valueOf (C[2][2]));
   
        for(int i=0;i<3;i++){
            for(int j=0;j<3;j++){

                System.out.print ("|"+ C[i][j]  +"|");
            }
            System.out.println ();
        }
    }//GEN-LAST:event_MULTIActionPerformed

    private void RESTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESTAActionPerformed
        // TODO add your handling code here:
        int [][] A = new int[3][3];
        A[0][0]=Integer.parseInt(A11.getText());
        A[0][1]=Integer.parseInt(A12.getText());
        A[0][2]=Integer.parseInt(A13.getText());
        A[1][0]=Integer.parseInt(A21.getText());
        A[1][1]=Integer.parseInt(A22.getText());
        A[1][2]=Integer.parseInt(A23.getText());
        A[2][0]=Integer.parseInt(A31.getText());
        A[2][1]=Integer.parseInt(A32.getText());
        A[2][2]=Integer.parseInt(A33.getText());
     
        int [][] B = new int[3][3];
        B[0][0]=Integer.parseInt(B11.getText());
        B[0][1]=Integer.parseInt(B12.getText());
        B[0][2]=Integer.parseInt(B13.getText());
        B[1][0]=Integer.parseInt(B21.getText());
        B[1][1]=Integer.parseInt(B22.getText());
        B[1][2]=Integer.parseInt(B23.getText());
        B[2][0]=Integer.parseInt(B31.getText());
        B[2][1]=Integer.parseInt(B32.getText());
        B[2][2]=Integer.parseInt(B33.getText());
       int [][] C = new int[3][3];
       
         C[0][0] = A[0][0] -  B[0][0]; 
         C[0][1]=  A[0][1] -  B[0][1]; 
         C[0][2]=  A[0][2] -  B[0][2]; 
         C[1][0]=  A[1][0] -  B[1][0]; 
         C[1][1]=  A[1][1] -  B[1][1]; 
         C[1][2]=  A[1][2] -  B[1][2]; 
         C[2][0]=  A[2][0] -  B[2][0]; 
         C[2][1]=  A[2][1] -  B[2][1]; 
         C[2][2]=  A[2][2] -  B[2][2]; 
         C11.setText(String.valueOf (C[0][0]));
         C12.setText(String.valueOf (C[0][1]));
         C13.setText(String.valueOf (C[0][2]));
         C21.setText(String.valueOf (C[1][0]));
         C22.setText(String.valueOf (C[1][1]));
         C23.setText(String.valueOf (C[1][2]));
         C31.setText(String.valueOf (C[2][0]));
         C32.setText(String.valueOf (C[2][1]));
         C33.setText(String.valueOf (C[2][2]));
   
        for(int i=0;i<3;i++){
            for(int j=0;j<3;j++){

                System.out.print ("|"+ C[i][j]  +"|");
            }
            System.out.println ();
        }                                          
    }//GEN-LAST:event_RESTAActionPerformed

    private void A11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A11ActionPerformed

    private void A11InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_A11InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_A11InputMethodTextChanged

    private void INVERSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INVERSAActionPerformed
        // TODO add your handling code here:
        int [][] A = new int[3][3];
        A[0][0]=Integer.parseInt(A11.getText());
        A[0][1]=Integer.parseInt(A12.getText());
        A[0][2]=Integer.parseInt(A13.getText());
        A[1][0]=Integer.parseInt(A21.getText());
        A[1][1]=Integer.parseInt(A22.getText());
        A[1][2]=Integer.parseInt(A23.getText());
        A[2][0]=Integer.parseInt(A31.getText());
        A[2][1]=Integer.parseInt(A32.getText());
        A[2][2]=Integer.parseInt(A33.getText());
        
 int determinante,determinante1,determinante2;
determinante = A[0][0] * A[1][1] * A[2] [2] + A[0] [1] *  A[1] [2] *  A[2] [0] +  A[1] [0] *  A[2] [1] *  A[0] [2] ;
determinante1= A[2][0] * A[1][1] * A[0] [2] + A[1] [0] *  A[0] [1] *  A[2] [2] +  A[2] [1] *  A[1] [2]*   A[0] [0] ;
  determinante2=determinante-determinante1;
  ax.setText(String.valueOf (determinante2));
  System.out.println ("Determinante: " + determinante2);
  
  int resul11,resul12,resul13,resul21,resul22,resul23,resul31,resul32,resul33;

        // cofactor 11
resul11 = A[1][1]* A[2][2] - A[2][1]* A[1][2] ;
resul11 = resul11 * 1;
//cofactor 12
resul12=A[1][0]* A[2][2] - A[2][0]* A[1][2] ;
resul12 = resul12 * -1;
//cofactor 1,3
resul13=A[1][0]* A[2][1] - A[2][0]* A[1][1] ;
resul13 = resul13 * 1;
//cofactor 21
resul21=A[0][1]* A[2][2] - A[2][1]* A[0][2] ;
resul21 = resul21 * -1;
//cofactor 22
resul22=A[0][0]* A[2][2] - A[2][0]* A[0][2] ;
resul22 = resul22 * 1;
//cofactor 23
resul23=A[0][0]* A[2][1] - A[2][0]* A[0][1] ;
resul23 = resul23 * -1;
//cofactor 31
resul31=A[0][1]* A[1][2] - A[1][1]* A[0][2] ;
resul31 = resul31 * 1;
//cofactor 32
resul32=A[0][0]* A[1][2] - A[1][0]* A[0][2] ;
resul32 = resul32 * -1;
//cofactor 33
resul33=A[0][0]* A[1][1] - A[1][0]* A[0][1] ;
resul33 = resul33 * 1;
 
  C11.setText(String.valueOf ( resul11  + "/" +  determinante2));
  C21.setText(String.valueOf (resul12+ "/" +  determinante2));
  C31.setText(String.valueOf (resul13+ "/" +  determinante2));
  C12.setText(String.valueOf (resul21+ "/" +  determinante2));
  C22.setText(String.valueOf (resul22+ "/" +  determinante2));
  C32.setText(String.valueOf (resul23+ "/" +  determinante2));
  C13.setText(String.valueOf (resul31+ "/" +  determinante2));
  C23.setText(String.valueOf (resul32+ "/" +  determinante2));
  C33.setText(String.valueOf (resul33+ "/" +  determinante2));
    }//GEN-LAST:event_INVERSAActionPerformed

    private void SUMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUMAActionPerformed
        // TODO add your handling code here:
        int [][] A = new int[3][3];
        A[0][0]=Integer.parseInt(A11.getText());
        A[0][1]=Integer.parseInt(A12.getText());
        A[0][2]=Integer.parseInt(A13.getText());
        A[1][0]=Integer.parseInt(A21.getText());
        A[1][1]=Integer.parseInt(A22.getText());
        A[1][2]=Integer.parseInt(A23.getText());
        A[2][0]=Integer.parseInt(A31.getText());
        A[2][1]=Integer.parseInt(A32.getText());
        A[2][2]=Integer.parseInt(A33.getText());
     
        int [][] B = new int[3][3];
        B[0][0]=Integer.parseInt(B11.getText());
        B[0][1]=Integer.parseInt(B12.getText());
        B[0][2]=Integer.parseInt(B13.getText());
        B[1][0]=Integer.parseInt(B21.getText());
        B[1][1]=Integer.parseInt(B22.getText());
        B[1][2]=Integer.parseInt(B23.getText());
        B[2][0]=Integer.parseInt(B31.getText());
        B[2][1]=Integer.parseInt(B32.getText());
        B[2][2]=Integer.parseInt(B33.getText());
       int [][] C = new int[3][3];
       
         C[0][0]= A[0][0] +  B[0][0]; 
         C[0][1]=  A[0][1] +  B[0][1]; 
         C[0][2]=  A[0][2] +  B[0][2]; 
         C[1][0]=  A[1][0] +  B[1][0]; 
         C[1][1]=  A[1][1] +  B[1][1]; 
         C[1][2]=  A[1][2] +  B[1][2]; 
         C[2][0]=  A[2][0] +  B[2][0]; 
         C[2][1]=  A[2][1] +  B[2][1]; 
         C[2][2]=  A[2][2] +  B[2][2]; 
         C11.setText(String.valueOf (C[0][0]));
         C12.setText(String.valueOf (C[0][1]));
         C13.setText(String.valueOf (C[0][2]));
         C21.setText(String.valueOf (C[1][0]));
         C22.setText(String.valueOf (C[1][1]));
         C23.setText(String.valueOf (C[1][2]));
         C31.setText(String.valueOf (C[2][0]));
         C32.setText(String.valueOf (C[2][1]));
         C33.setText(String.valueOf (C[2][2]));
   
        for(int i=0;i<3;i++){
            for(int j=0;j<3;j++){
             
                System.out.print ("|"+ C[i][j]  +"|");
            }
            System.out.println ();                        
        }             
    }//GEN-LAST:event_SUMAActionPerformed

    private void DetAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetAActionPerformed
        // TODO add your handling code here:
         int [][] A = new int[3][3];
        A[0][0]=Integer.parseInt(A11.getText());
        A[0][1]=Integer.parseInt(A12.getText());
        A[0][2]=Integer.parseInt(A13.getText());
        A[1][0]=Integer.parseInt(A21.getText());
        A[1][1]=Integer.parseInt(A22.getText());
        A[1][2]=Integer.parseInt(A23.getText());
        A[2][0]=Integer.parseInt(A31.getText());
        A[2][1]=Integer.parseInt(A32.getText());
        A[2][2]=Integer.parseInt(A33.getText());
        
 int determinante,determinante1,determinante2;
determinante = A[0][0] * A[1][1] * A[2] [2] + A[0] [1] *  A[1] [2] *  A[2] [0] +  A[1] [0] *  A[2] [1] *  A[0] [2] ;
determinante1= A[2][0] * A[1][1] * A[0] [2] + A[1] [0] *  A[0] [1] *  A[2] [2] +  A[2] [1] *  A[1] [2]*   A[0] [0] ;
  determinante2=determinante-determinante1;
  ax.setText(String.valueOf (determinante2));
  System.out.println ("Determinante: " + determinante2);
    }//GEN-LAST:event_DetAActionPerformed

    private void CLEANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEANActionPerformed
        // TODO add your handling code here:
        ax.setText("");
        JTextField caja;
        for (int i = 0; i < MatrizA.getComponentCount(); i++)
        {
            if(MatrizA.getComponent(i).getClass().getName().equals("javax.swing.JTextField"))
            {
                caja = (JTextField)MatrizA.getComponent(i);
                caja.setText("");
            }
        }
        for (int i = 0; i < MatrizB.getComponentCount(); i++)
        {
            if(MatrizB.getComponent(i).getClass().getName().equals("javax.swing.JTextField"))
            {
                caja = (JTextField)MatrizB.getComponent(i);
                caja.setText("");
            }
        }
        for (int i = 0; i < MatrizC.getComponentCount(); i++)
        {
            if(MatrizC.getComponent(i).getClass().getName().equals("javax.swing.JTextField"))
            {
                caja = (JTextField)MatrizC.getComponent(i);
                caja.setText("");
            }
        }
    }//GEN-LAST:event_CLEANActionPerformed

    private void TrasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrasAActionPerformed
        // TODO add your handling code here:
        int valor1 =Integer.parseInt(A11.getText());
                int valor2 =Integer.parseInt(A12.getText());
                int valor3 =Integer.parseInt(A13.getText());
                int valor4 =Integer.parseInt(A21.getText());
                int valor5 =Integer.parseInt(A22.getText());
                int valor6 =Integer.parseInt(A23.getText());
                int valor7 =Integer.parseInt(A31.getText());
                int valor8 =Integer.parseInt(A32.getText());
                int valor9 =Integer.parseInt(A33.getText());
                
                C11.setText(String.valueOf (valor1));
                C12.setText(String.valueOf (valor4)); 
                C13.setText(String.valueOf (valor7)); 
                C21.setText(String.valueOf (valor2)); 
                C22.setText(String.valueOf (valor5)); 
                C23.setText(String.valueOf (valor8)); 
                C31.setText(String.valueOf (valor3)); 
                C32.setText(String.valueOf (valor6)); 
                C33.setText(String.valueOf (valor9)); 
    }//GEN-LAST:event_TrasAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A11;
    private javax.swing.JTextField A12;
    private javax.swing.JTextField A13;
    private javax.swing.JTextField A21;
    private javax.swing.JTextField A22;
    private javax.swing.JTextField A23;
    private javax.swing.JTextField A31;
    private javax.swing.JTextField A32;
    private javax.swing.JTextField A33;
    private javax.swing.JTextField B11;
    private javax.swing.JTextField B12;
    private javax.swing.JTextField B13;
    private javax.swing.JTextField B21;
    private javax.swing.JTextField B22;
    private javax.swing.JTextField B23;
    private javax.swing.JTextField B31;
    private javax.swing.JTextField B32;
    private javax.swing.JTextField B33;
    private javax.swing.JTextField C11;
    private javax.swing.JTextField C12;
    private javax.swing.JTextField C13;
    private javax.swing.JTextField C21;
    private javax.swing.JTextField C22;
    private javax.swing.JTextField C23;
    private javax.swing.JTextField C31;
    private javax.swing.JTextField C32;
    private javax.swing.JTextField C33;
    private javax.swing.JButton CLEAN;
    private javax.swing.JLabel Det;
    private javax.swing.JButton DetA;
    private javax.swing.JButton INVERSA;
    private javax.swing.JButton MULTI;
    private javax.swing.JLabel Marca1;
    private javax.swing.JPanel MatrizA;
    private javax.swing.JPanel MatrizB;
    private javax.swing.JPanel MatrizC;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton RESTA;
    private javax.swing.JButton SUMA;
    private javax.swing.JLabel TITULO;
    private javax.swing.JLabel TagA;
    private javax.swing.JLabel TagB;
    private javax.swing.JLabel TagC;
    private javax.swing.JButton TrasA;
    private javax.swing.JLabel ax;
    // End of variables declaration//GEN-END:variables
}
